*** Settings ***

Documentation    Arquivo que importa todas as pages

### All pages resource ###
Resource    page_onboarding.resource
Resource    page_login.resource
Resource    page_cadastro.resource
Resource    page_acessoDeslogado.resource
Resource    page_meu_perfil_deslogado.resource
Resource    page_anotacoes.resource
Resource    page_destaque.resource
Resource    page_realces.resource
Resource    page_sublinhados.resource
Resource    page_trocarIdioma.resource
Resource    page_configuracoes.resource
Resource    page_assinaturas.resource