*** Settings ***

Documentation     Arquivo com locators da page realces

*** Variables ***

${header_realces}                 //android.widget.TextView[@resource-id="org.universal.bibliafiel_comentada:id/txtToolbarTitle" and @text="Highlights"]
${btn_voltar_realces}             //android.widget.ImageButton[@content-desc="Navigate up"]
${btn_check_realces}              //android.widget.Button[@resource-id="org.universal.bibliafiel_comentada:id/item_highlight_selector"]
${btn_texto_biblico_realces}      //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radLeft"]
${btn_comentarios_realces}        //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radRight"]
${btn_cores_realces}              //android.widget.TextView[@text="Colors"]
${btn_categorias_realces}         //android.widget.TextView[@text="Categories"]
${btn_tags_realces}               //android.widget.TextView[@text="Tags"]
${btn_ver_tudo_realces}           //android.widget.TextView[@text="See all"]
