*** Settings ***

Documentation     Arquivo com locators da page destaque

*** Variables ***

${header_destaque}            //android.widget.TextView[@resource-id="org.universal.bibliafiel_comentada:id/txtToolbarTitle" and @text="Highlights"]
${btn_voltar_destaque}        //android.widget.ImageButton[@content-desc="Navigate up"]
${btn_realces}                //android.widget.TextView[@resource-id="org.universal.bibliafiel_comentada:id/txtHighlightTitle"]
${btn_sublinhados}            //android.widget.TextView[@resource-id="org.universal.bibliafiel_comentada:id/txtUnderlineTitle"]