*** Settings ***

Documentation     Arquivo com locators da page de configuracoes

*** Variables ***

${btn_brilho}        //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radBrightness"]
${btn_fonte}         //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radFont"]
${btn_tema}          //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radTheme"]
${barra_brilho}      //android.widget.SeekBar[@resource-id="org.universal.bibliafiel_comentada:id/sbBrightness"]