*** Settings ***

Documentation     Arquivo com locators da page de configuracoes

*** Variables ***

${btn_brilho}                      //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radBrightness"]
${btn_fonte}                       //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radFont"]
${btn_tema}                        //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radTheme"]
${barra_brilho}                    //android.widget.SeekBar[@resource-id="org.universal.bibliafiel_comentada:id/sbBrightness"]
${formato_texto}                   //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radTextFormat"]
${small_space}                     //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radSpaceSmall"]
${medium_space}                    //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radSpaceMedium"]
${big_space}                       //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radSpaceBig"]
${alinhamento_esquerda}            //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radAlignmentLeft"]
${alinhamento_centralizado}        //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radAlignmentCenter"]
${alinhamento_direita}             //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radAlignmentRight"]
${estilo_normal}                   //android.widget.CheckBox[@resource-id="org.universal.bibliafiel_comentada:id/cbStyleNormal"]
${estilo_negrito}                  //android.widget.CheckBox[@resource-id="org.universal.bibliafiel_comentada:id/cbStyleBold"]
${estilo_italico}                  //android.widget.CheckBox[@resource-id="org.universal.bibliafiel_comentada:id/cbStyleItalic"]
${barra_tamanho}                   //android.widget.SeekBar[@resource-id="org.universal.bibliafiel_comentada:id/sbTextSize"]
${btn_cor}                         //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radTextColor"]
${btn_tema}                        //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radTheme"]
${btn_claro}                       //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radLight"]
${btn_escuro}                      //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radDark"]
${btn_device}                      //android.widget.RadioButton[@resource-id="org.universal.bibliafiel_comentada:id/radSystem"]