*** Settings ***


Resource    ../../resources/keywords/app_keywords.robot
Resource    ../../resources/keywords/kws_onboarding.robot
Resource    ../../resources/keywords/kws_cadastro.robot
Resource    ../../resources/keywords/kws_acessoDeslogado.robot
Resource    ../../resources/keywords/kws_meu_perfil.robot
Resource    ../../resources/keywords/kws_anotacoes.robot
Resource    ../../resources/keywords/kws_destaque.robot